### ISSUE TITLE
Doesn't work with pagination

### ISSUE THREAD

**Issue by lukecurtis93** [jackpopp/geodistance#12]
Hi All,

Just a quick one, it appears that this won't work when attempting to use Laravels built in pagination method.

Not sure if I'm doing this wrong but I can replicate it with the following:

Even getting a generic collection of anything, in this example I'll use a holiday:

```
$response = \Geocode::make()->address('ME10 4PB');
$lat = $response->latitude();
$lng = $response->longitude();

$holidays = \App\Holiday::within(5, 'miles', $lat, $lng)->get();
```
This will work with `get()`, however when doing the following:

```
$response = \Geocode::make()->address('ME10 4PB');
$lat = $response->latitude();
$lng = $response->longitude();

$holidays = \App\Holiday::within(5, 'miles', $lat, $lng)->paginate(5);
```

The following error occurs:

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'distance' in 'having clause' (SQL: select count(*) as aggregate from (
Select *
From holidays
Where holidays.lat Between 51.267621070961 And 51.412343929039
And holidays.lng Between 0.62098592375332 And 0.85265447624668
) As holidays where `guests` >= 1 having `distance` <= 5)
```

**Comment by selfpaidinc** [comment]
Same here, would like to see pagination capability added. Currently I switched over to an ugly scope;

<pre>
public static function scopeGetByDistance($query, $lat, $lng, $distance)
{
	$results = DB::select(DB::raw('SELECT id, ( 3959 * acos( cos( radians(' . $lat . ') ) * cos( radians( lat ) ) * cos( radians( lng ) - radians(' . $lng . ') ) + sin( radians(' . $lat .') ) * sin( radians(lat) ) ) ) AS distance FROM users HAVING distance < ' . $distance . ' ORDER BY distance') );
	if(!empty($results)) {
		$ids = [];
		foreach($results as $q) {
			array_push($ids, $q->id);
		}
		return $query->whereIn('id',$ids)->orderBy('id','desc');
	}
	return $query;
}
</pre>

use like:
`Model::GetByDistance($latitude, $longitude, $distance)->paginate(20)`

this is for distance in miles.

**Comment by lukecurtis93** [comment]
Thanks, thats a great workaround for now :)

**Comment by andylobel** [comment]
Hey @lukecurtis93 and @selfpaidinc 

See my other issue on the best way to use this with pagination:
https://github.com/jackpopp/geodistance/issues/13
