### ISSUE TITLE
Lat/Lng setters/getters bug.

### ISSUE THREAD

**Issue by jan-j** [jackpopp/geodistance#2]
Lat or lng could be 0, but when using setter `lat($lat)` or `lng($lng)`, 0 is treated as no value and new value is not set. Function `is_null` probably would solve this issue.

https://github.com/jackpopp/geodistance/blob/master/src/Jackpopp/GeoDistance/GeoDistanceTrait.php#L46

**Comment by jackpopp** [comment]
Thanks for pointing this out, fixed it and pushed it. 

Thanks!
