### ISSUE TITLE
Using Postgres I get an error about no distance column.

### ISSUE THREAD

**Issue by jonnybarnes** [jackpopp/geodistance#7]
Here’s the full error message:

```
SQLSTATE[42703]: Undefined column: 7 ERROR: column "distance" does not exist LINE 6: ...places where "places"."deleted_at" is null having "distance"... ^ (SQL: select *, ( '3959' * acos( cos( radians('53.49') ) * cos( radians( places.lat ) ) * cos( radians( places.lng ) - radians('-2.38') ) + sin( radians('53.49') ) * sin( radians( places.lat ) ) ) ) AS distance from ( Select * From places Where places.lat Between 53.475527714192 And 53.504472285808 And places.lng Between -2.4043246788967 And -2.3556753211033 ) As places where "places"."deleted_at" is null having "distance" <= 1 order by "distance" asc) 
```

**Comment by jonnybarnes** [comment]
Maybe more specific this is in postgres’ `server.log`:

```
ERROR:  column "distance" does not exist at character 507
STATEMENT:  select *, ( '3959' * acos( cos( radians('53.49') ) * cos( radians( places.lat ) ) * cos( radians( places.lng ) - radians('-2.38') ) + sin( radians('53.49') ) * sin( radians( places.lat ) ) ) ) AS distance from (
                        Select *
                        From places
                        Where places.lat Between 53.475527714192 And 53.504472285808
                        And places.lng Between -2.4043246788967 And -2.3556753211033
                    ) As places where "places"."deleted_at" is null having "distance" <= $1 order by "distance" asc
```

**Comment by jackpopp** [comment]
It looks like the SQL that is generated only works with mySQL and is invalid for postgres.
I'll try and get a working query for postgres as soon as I can.

**Comment by jackpopp** [comment]
Looks like postgres doesn't execute the select first, so when distance is referenced it doesn't exist yet. Hopefully this can be fixed by doing the distance calc again within the having. I'll try this tonight.

**Comment by jackpopp** [comment]
I've updated with a fix, if you'd like to test out the branch and see if it works for you then I will merge into master. I've only tried with a simple mode/query test so it would be good to see if it works in a more complex setup as postgres is a lot more unforgiving than mysql.

Just update composer to use:

`"jackpopp/geodistance": "dev-query_adapters"`

**Comment by jonnybarnes** [comment]
Okay, that works. But I’m not sure I like the calculating the distance twice. It seems the proper way of doing this is with derived tables. The following raw SQL query works with both MySQL and PostgreSQL, with the appropriate table/column names etc:

```
select *
from (
    select *,
        (
            3959 * acos(cos(radians(53.49)) * cos(radians(places.lat)) * cos(radians(places.lng) - radians(-2.38)) + sin(radians(53.49)) * sin(radians(places.lat)))
        ) AS distance
    from (
        select *
        from places
        where places.lat between 53.475527714192 and 53.504472285808
        and places.lng between -2.4043246788967 and -2.3556753211033
    ) as places
where places.deleted_at is null
) sub
where distance <= 1
order by distance asc
```

But I keep failing trying to get that working with Laravel’s query scopes.
